"""demo slice domains

Revision ID: 0003
Revises: 0002
Create Date: 2026-08-18 14:51:50.670081
"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kb_candidates",
        sa.Column("term", sa.String(length=60), nullable=False),
        sa.Column("gloss", sa.Text(), nullable=True),
        sa.Column("detected_confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','APPROVED','REJECTED')",
            name=op.f("ck_kb_candidates_status_allowed"),
        ),
        sa.CheckConstraint(
            "detected_confidence BETWEEN 0 AND 1", name=op.f("ck_kb_candidates_confidence_range")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_candidates")),
    )
    op.create_table(
        "kb_norms",
        sa.Column("id", sa.String(length=6), nullable=False),
        sa.Column("claim", sa.Text(), nullable=False),
        sa.Column("scope_locale", sa.String(length=2), nullable=False),
        sa.Column("scope_context", sa.String(length=32), nullable=False),
        sa.Column("sources", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("verified_at", sa.Date(), nullable=False),
        sa.Column("confidence", sa.Numeric(precision=3, scale=2), nullable=False),
        sa.Column("disputes", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.CheckConstraint("id ~ '^[A-Z]{2}-[0-9]{3}$'", name=op.f("ck_kb_norms_id_pattern")),
        sa.CheckConstraint(
            "status <> 'ACTIVE' OR jsonb_array_length(sources) >= 2",
            name=op.f("ck_kb_norms_sources_min"),
        ),
        sa.CheckConstraint(
            "status IN ('ACTIVE','RETIRED','CANDIDATE')", name=op.f("ck_kb_norms_status_allowed")
        ),
        sa.CheckConstraint("confidence BETWEEN 0 AND 1", name=op.f("ck_kb_norms_confidence_range")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_kb_norms")),
    )
    op.create_table(
        "notifications",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("resource_type", sa.String(length=32), nullable=True),
        sa.Column("resource_id", sa.UUID(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind IN ('APPLICATION_RECEIVED','APPLICATION_ACCEPTED','APPLICATION_REJECTED','DEPOSIT_UPDATED','MESSAGE_RECEIVED','COMPLETION_REQUESTED','COLLABORATION_COMPLETED','REVIEW_RECEIVED')",
            name=op.f("ck_notifications_kind_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(
        "ix_notifications_user_created", "notifications", ["user_id", "created_at"], unique=False
    )
    op.create_table(
        "signals",
        sa.Column("requester_profile_id", sa.UUID(), nullable=False),
        sa.Column("signal_type", sa.String(length=16), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("moderation_status", sa.String(length=24), nullable=False),
        sa.Column("matching_mode", sa.String(length=16), nullable=False),
        sa.Column("visibility", sa.String(length=16), nullable=False),
        sa.Column("source_language", sa.String(length=2), nullable=False),
        sa.Column("urgency", sa.String(length=16), nullable=False),
        sa.Column("requires_physical_presence", sa.Boolean(), nullable=False),
        sa.Column("area_hint", sa.String(length=60), nullable=True),
        sa.Column("location_city_code", sa.String(length=32), nullable=True),
        sa.Column("target_is_team", sa.Boolean(), nullable=False),
        sa.Column("team_cardinality", sa.String(length=4), nullable=False),
        sa.Column("headcount_hint", sa.SmallInteger(), nullable=True),
        sa.Column("duration_weeks", sa.SmallInteger(), nullable=True),
        sa.Column("duration_origin", sa.String(length=16), nullable=False),
        sa.Column("compensation_is_paid", sa.Boolean(), nullable=False),
        sa.Column("compensation_amount_minor", sa.Integer(), nullable=True),
        sa.Column("compensation_currency", sa.String(length=3), nullable=True),
        sa.Column("compensation_origin", sa.String(length=16), nullable=False),
        sa.Column("license_risk_flagged", sa.Boolean(), nullable=False),
        sa.Column("license_risk_kind", sa.String(length=16), nullable=False),
        sa.Column("license_risk_acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("required_credentials", postgresql.ARRAY(sa.String(length=32)), nullable=False),
        sa.Column("high_risk_acknowledged_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("inference_confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("policy_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(signal_type = 'CIRCLE' AND compensation_is_paid = false) OR (signal_type IN ('WORK','BOOKING') AND compensation_is_paid = true) OR signal_type = 'HELP'",
            name=op.f("ck_signals_type_compensation_rule"),
        ),
        sa.CheckConstraint(
            "compensation_origin IN ('EXPLICIT','INFERRED','NONE')",
            name=op.f("ck_signals_compensation_origin_allowed"),
        ),
        sa.CheckConstraint(
            "duration_origin IN ('EXPLICIT','INFERRED','DEFAULT','NONE')",
            name=op.f("ck_signals_duration_origin_allowed"),
        ),
        sa.CheckConstraint(
            "license_risk_kind IN ('DERIVATIVE_IP','TRADEMARK','NONE')",
            name=op.f("ck_signals_license_kind_allowed"),
        ),
        sa.CheckConstraint(
            "matching_mode IN ('MATCH','RECRUITMENT')",
            name=op.f("ck_signals_matching_mode_allowed"),
        ),
        sa.CheckConstraint(
            "moderation_status IN ('ALLOWED','PENDING_REVIEW','BLOCKED','SELF_HARM_ROUTE')",
            name=op.f("ck_signals_moderation_allowed"),
        ),
        sa.CheckConstraint(
            "signal_type IN ('HELP','WORK','CIRCLE','BOOKING')",
            name=op.f("ck_signals_signal_type_allowed"),
        ),
        sa.CheckConstraint(
            "source_language ~ '^[a-z]{2}$'", name=op.f("ck_signals_source_language_two_letters")
        ),
        sa.CheckConstraint(
            "status IN ('DRAFT','OPEN','PAUSED','IN_PROGRESS','CLOSED','EXPIRED','CANCELLED','COMPLETED')",
            name=op.f("ck_signals_status_allowed"),
        ),
        sa.CheckConstraint(
            "team_cardinality IN ('1:1','1:N','N:N')", name=op.f("ck_signals_cardinality_allowed")
        ),
        sa.CheckConstraint(
            "urgency IN ('CRITICAL','HIGH','NORMAL','LOW')", name=op.f("ck_signals_urgency_allowed")
        ),
        sa.CheckConstraint(
            "visibility IN ('PUBLIC','LINK_ONLY','PRIVATE')",
            name=op.f("ck_signals_visibility_allowed"),
        ),
        sa.CheckConstraint(
            "(compensation_amount_minor IS NULL AND compensation_currency IS NULL) OR (compensation_amount_minor IS NOT NULL AND compensation_currency IS NOT NULL)",
            name=op.f("ck_signals_compensation_pairing"),
        ),
        sa.CheckConstraint(
            "char_length(raw_text) BETWEEN 1 AND 4000", name=op.f("ck_signals_raw_text_length")
        ),
        sa.CheckConstraint(
            "compensation_is_paid = true OR compensation_amount_minor IS NULL",
            name=op.f("ck_signals_unpaid_has_no_amount"),
        ),
        sa.CheckConstraint(
            "duration_weeks IS NULL OR duration_weeks BETWEEN 1 AND 104",
            name=op.f("ck_signals_duration_range"),
        ),
        sa.CheckConstraint(
            "headcount_hint IS NULL OR headcount_hint BETWEEN 1 AND 50",
            name=op.f("ck_signals_headcount_range"),
        ),
        sa.ForeignKeyConstraint(
            ["requester_profile_id"],
            ["profiles.id"],
            name=op.f("fk_signals_requester_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signals")),
    )
    op.create_index(
        "ix_signals_status_published_at", "signals", ["status", "published_at"], unique=False
    )
    op.create_table(
        "collaborations",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=120), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("deposit_applies", sa.Boolean(), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('AGREEMENT_PENDING','DEPOSIT_PENDING','ACTIVE','COMPLETION_PENDING','COMPLETED','DISPUTED','CANCELLED')",
            name=op.f("ck_collaborations_status_allowed"),
        ),
        sa.CheckConstraint(
            "char_length(title) BETWEEN 1 AND 120", name=op.f("ck_collaborations_title_length")
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_collaborations_signal_id_signals"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collaborations")),
    )
    op.create_table(
        "signal_roles",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("label", sa.String(length=40), nullable=False),
        sa.Column("normalized_label", sa.String(length=40), nullable=False),
        sa.Column("headcount", sa.SmallInteger(), nullable=True),
        sa.Column("filled_count", sa.SmallInteger(), nullable=False),
        sa.Column("source", sa.String(length=16), nullable=False),
        sa.Column("form_position", sa.SmallInteger(), nullable=False),
        sa.Column("evidence_span", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "source = 'USER_FORM'", name=op.f("ck_signal_roles_source_user_form_only")
        ),
        sa.CheckConstraint(
            "char_length(label) BETWEEN 1 AND 40", name=op.f("ck_signal_roles_label_length")
        ),
        sa.CheckConstraint("filled_count >= 0", name=op.f("ck_signal_roles_filled_non_negative")),
        sa.CheckConstraint(
            "form_position BETWEEN 0 AND 7", name=op.f("ck_signal_roles_form_position_range")
        ),
        sa.CheckConstraint(
            "headcount IS NULL OR headcount BETWEEN 1 AND 50",
            name=op.f("ck_signal_roles_headcount_range"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_signal_roles_signal_id_signals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_roles")),
        sa.UniqueConstraint("signal_id", "form_position", name=op.f("uq_signal_roles_signal_id")),
    )
    op.create_table(
        "signal_skills",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("skill_name", sa.String(length=40), nullable=False),
        sa.Column("origin", sa.String(length=16), nullable=False),
        sa.Column("evidence_span", sa.Text(), nullable=True),
        sa.Column("confirmation_status", sa.String(length=16), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confirmation_status IN ('NOT_REQUIRED','PENDING','CONFIRMED','REJECTED')",
            name=op.f("ck_signal_skills_confirmation_allowed"),
        ),
        sa.CheckConstraint(
            "origin IN ('EXPLICIT','INFERRED','USER_EDITED')",
            name=op.f("ck_signal_skills_origin_allowed"),
        ),
        sa.CheckConstraint(
            "char_length(skill_name) BETWEEN 1 AND 40",
            name=op.f("ck_signal_skills_skill_name_length"),
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_signal_skills_signal_id_signals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_signal_skills")),
    )
    op.create_table(
        "applications",
        sa.Column("signal_id", sa.UUID(), nullable=False),
        sa.Column("applicant_profile_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=True),
        sa.Column("direction", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "direction IN ('APPLICATION','INVITATION')",
            name=op.f("ck_applications_direction_allowed"),
        ),
        sa.CheckConstraint(
            "status IN ('PENDING','ACCEPTED','REJECTED','WITHDRAWN')",
            name=op.f("ck_applications_status_allowed"),
        ),
        sa.CheckConstraint(
            "char_length(message) <= 1000", name=op.f("ck_applications_message_length")
        ),
        sa.ForeignKeyConstraint(
            ["applicant_profile_id"],
            ["profiles.id"],
            name=op.f("fk_applications_applicant_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["signal_roles.id"],
            name=op.f("fk_applications_role_id_signal_roles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["signal_id"],
            ["signals.id"],
            name=op.f("fk_applications_signal_id_signals"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_applications")),
        sa.UniqueConstraint(
            "signal_id", "applicant_profile_id", "direction", name=op.f("uq_applications_signal_id")
        ),
    )
    op.create_table(
        "collaboration_deliverables",
        sa.Column("collaboration_id", sa.UUID(), nullable=False),
        sa.Column("file_name", sa.String(length=120), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("position", sa.SmallInteger(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "content_hash ~ '^[0-9a-f]{64}$'",
            name=op.f("ck_collaboration_deliverables_hash_sha256"),
        ),
        sa.CheckConstraint(
            "char_length(file_name) BETWEEN 1 AND 120",
            name=op.f("ck_collaboration_deliverables_file_name_length"),
        ),
        sa.ForeignKeyConstraint(
            ["collaboration_id"],
            ["collaborations.id"],
            name=op.f("fk_collaboration_deliverables_collaboration_id_collaborations"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collaboration_deliverables")),
        sa.UniqueConstraint(
            "collaboration_id",
            "position",
            name=op.f("uq_collaboration_deliverables_collaboration_id"),
        ),
    )
    op.create_table(
        "collaboration_members",
        sa.Column("collaboration_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("role_label", sa.String(length=40), nullable=False),
        sa.Column("is_requester", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "char_length(role_label) BETWEEN 1 AND 40",
            name=op.f("ck_collaboration_members_role_label_length"),
        ),
        sa.ForeignKeyConstraint(
            ["collaboration_id"],
            ["collaborations.id"],
            name=op.f("fk_collaboration_members_collaboration_id_collaborations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_collaboration_members_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_collaboration_members")),
        sa.UniqueConstraint(
            "collaboration_id", "profile_id", name=op.f("uq_collaboration_members_collaboration_id")
        ),
    )
    op.create_table(
        "completion_confirmations",
        sa.Column("collaboration_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collaboration_id"],
            ["collaborations.id"],
            name=op.f("fk_completion_confirmations_collaboration_id_collaborations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_completion_confirmations_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_completion_confirmations")),
        sa.UniqueConstraint(
            "collaboration_id",
            "profile_id",
            name=op.f("uq_completion_confirmations_collaboration_id"),
        ),
    )
    op.create_table(
        "conversations",
        sa.Column("collaboration_id", sa.UUID(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["collaboration_id"],
            ["collaborations.id"],
            name=op.f("fk_conversations_collaboration_id_collaborations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_conversations")),
        sa.UniqueConstraint("collaboration_id", name=op.f("uq_conversations_collaboration_id")),
    )
    op.create_table(
        "deposit_agreements",
        sa.Column("collaboration_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("amount_minor_per_party", sa.BigInteger(), nullable=False),
        sa.Column("cap_policy_version", sa.String(length=32), nullable=False),
        sa.Column("terms_hash", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_deposit_agreements_currency_iso")
        ),
        sa.CheckConstraint(
            "status IN ('PROPOSED','AGREED','FUNDING','LOCKED','REFUND_PENDING','REFUNDED','DISPUTED','CANCELLED')",
            name=op.f("ck_deposit_agreements_status_allowed"),
        ),
        sa.CheckConstraint(
            "amount_minor_per_party > 0", name=op.f("ck_deposit_agreements_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["collaboration_id"],
            ["collaborations.id"],
            name=op.f("fk_deposit_agreements_collaboration_id_collaborations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deposit_agreements")),
        sa.UniqueConstraint(
            "collaboration_id", name=op.f("uq_deposit_agreements_collaboration_id")
        ),
    )
    op.create_table(
        "reviews",
        sa.Column("collaboration_id", sa.UUID(), nullable=False),
        sa.Column("reviewer_profile_id", sa.UUID(), nullable=False),
        sa.Column("reviewee_profile_id", sa.UUID(), nullable=False),
        sa.Column("rating", sa.String(length=16), nullable=False),
        sa.Column("tags", postgresql.ARRAY(sa.String(length=24)), nullable=False),
        sa.Column("comment", sa.Text(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "rating IN ('POSITIVE','NEUTRAL','NEGATIVE')", name=op.f("ck_reviews_rating_allowed")
        ),
        sa.CheckConstraint("char_length(comment) <= 500", name=op.f("ck_reviews_comment_length")),
        sa.CheckConstraint(
            "reviewer_profile_id <> reviewee_profile_id", name=op.f("ck_reviews_no_self_review")
        ),
        sa.ForeignKeyConstraint(
            ["collaboration_id"],
            ["collaborations.id"],
            name=op.f("fk_reviews_collaboration_id_collaborations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewee_profile_id"],
            ["profiles.id"],
            name=op.f("fk_reviews_reviewee_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["reviewer_profile_id"],
            ["profiles.id"],
            name=op.f("fk_reviews_reviewer_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reviews")),
        sa.UniqueConstraint(
            "collaboration_id",
            "reviewer_profile_id",
            "reviewee_profile_id",
            name=op.f("uq_reviews_collaboration_id"),
        ),
    )
    op.create_table(
        "trust_events",
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("event_key", sa.String(length=32), nullable=False),
        sa.Column("demo_delta", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("source_collaboration_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "(event_key = 'DEMO_SEED') = (demo_delta IS NOT NULL)",
            name=op.f("ck_trust_events_demo_delta_only_for_seed"),
        ),
        sa.CheckConstraint(
            "event_key IN ('COLLABORATION_COMPLETED','NO_SHOW_CONFIRMED','REVIEW_RECEIVED:POSITIVE','REVIEW_RECEIVED:NEUTRAL','REVIEW_RECEIVED:NEGATIVE','DISPUTE_RESOLVED:AT_FAULT','DISPUTE_RESOLVED:OTHER','DEMO_SEED')",
            name=op.f("ck_trust_events_event_key_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_trust_events_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["source_collaboration_id"],
            ["collaborations.id"],
            name=op.f("fk_trust_events_source_collaboration_id_collaborations"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trust_events")),
    )
    op.create_index(
        "ix_trust_events_profile_created",
        "trust_events",
        ["profile_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "deposit_ledger_entries",
        sa.Column("agreement_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("entry_type", sa.String(length=8), nullable=False),
        sa.Column("amount_minor", sa.BigInteger(), nullable=False),
        sa.Column("provider_event_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "entry_type IN ('FUND','REFUND')",
            name=op.f("ck_deposit_ledger_entries_entry_type_allowed"),
        ),
        sa.CheckConstraint(
            "amount_minor > 0", name=op.f("ck_deposit_ledger_entries_amount_positive")
        ),
        sa.ForeignKeyConstraint(
            ["agreement_id"],
            ["deposit_agreements.id"],
            name=op.f("fk_deposit_ledger_entries_agreement_id_deposit_agreements"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_deposit_ledger_entries_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deposit_ledger_entries")),
        sa.UniqueConstraint(
            "provider_event_id", name=op.f("uq_deposit_ledger_entries_provider_event_id")
        ),
    )
    op.create_table(
        "deposit_parties",
        sa.Column("agreement_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("agreed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("funded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("refunded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["agreement_id"],
            ["deposit_agreements.id"],
            name=op.f("fk_deposit_parties_agreement_id_deposit_agreements"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.id"],
            name=op.f("fk_deposit_parties_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_deposit_parties")),
        sa.UniqueConstraint(
            "agreement_id", "profile_id", name=op.f("uq_deposit_parties_agreement_id")
        ),
    )
    op.create_table(
        "guard_events",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("sender_profile_id", sa.UUID(), nullable=False),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("risk", sa.String(length=8), nullable=False),
        sa.Column("phenomenon", sa.String(length=32), nullable=False),
        sa.Column("choice", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default="now()", nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "choice IN ('ORIGINAL','SUGGESTION')", name=op.f("ck_guard_events_choice_allowed")
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_guard_events_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sender_profile_id"],
            ["profiles.id"],
            name=op.f("fk_guard_events_sender_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_guard_events")),
    )
    op.create_table(
        "messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column("sender_profile_id", sa.UUID(), nullable=False),
        sa.Column("client_message_id", sa.String(length=64), nullable=False),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("source_lang", sa.String(length=2), nullable=False),
        sa.Column("delivery_status", sa.String(length=24), nullable=False),
        sa.Column("moderation_status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "delivery_status IN ('ACCEPTED','DELIVERED','HELD_FOR_REVIEW','NOT_SENT_SAFETY_ROUTE','FAILED')",
            name=op.f("ck_messages_delivery_allowed"),
        ),
        sa.CheckConstraint(
            "moderation_status IN ('ALLOWED','PENDING_REVIEW','BLOCKED','SELF_HARM_ROUTE')",
            name=op.f("ck_messages_moderation_allowed"),
        ),
        sa.CheckConstraint(
            "source_lang ~ '^[a-z]{2}$'", name=op.f("ck_messages_source_lang_two_letters")
        ),
        sa.CheckConstraint(
            "char_length(source_text) BETWEEN 1 AND 2000",
            name=op.f("ck_messages_source_text_length"),
        ),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["conversations.id"],
            name=op.f("fk_messages_conversation_id_conversations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sender_profile_id"],
            ["profiles.id"],
            name=op.f("fk_messages_sender_profile_id_profiles"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_messages")),
        sa.UniqueConstraint(
            "conversation_id", "client_message_id", name=op.f("uq_messages_conversation_id")
        ),
    )
    op.create_index(
        "ix_messages_conversation_created",
        "messages",
        ["conversation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "lens_annotations",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("target_lang", sa.String(length=2), nullable=False),
        sa.Column("l1_literal", sa.Text(), nullable=False),
        sa.Column("l3_annotation", sa.Text(), nullable=True),
        sa.Column("l3_heading", sa.String(length=16), nullable=True),
        sa.Column("l3_level", sa.String(length=16), nullable=True),
        sa.Column("l3_kb_ids", postgresql.ARRAY(sa.String(length=8)), nullable=False),
        sa.Column("publishable", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "l3_level IN ('STRONG','MODERATE','REFERENCE') OR l3_level IS NULL",
            name=op.f("ck_lens_annotations_l3_level_allowed"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_lens_annotations_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_lens_annotations")),
        sa.UniqueConstraint(
            "message_id", "target_lang", name=op.f("uq_lens_annotations_message_id")
        ),
    )
    op.create_table(
        "message_translations",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("target_lang", sa.String(length=2), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('READY','UNSAFE_OR_FAILED','PENDING')",
            name=op.f("ck_message_translations_status_allowed"),
        ),
        sa.CheckConstraint(
            "target_lang ~ '^[a-z]{2}$'",
            name=op.f("ck_message_translations_target_lang_two_letters"),
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_translations_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_translations")),
        sa.UniqueConstraint(
            "message_id", "target_lang", name=op.f("uq_message_translations_message_id")
        ),
    )

    op.add_column("guard_events", sa.Column("message_id", sa.Uuid(), nullable=True))
    op.create_foreign_key(
        op.f("fk_guard_events_message_id_messages"),
        "guard_events",
        "messages",
        ["message_id"],
        ["id"],
        ondelete="SET NULL",
    )


def downgrade() -> None:
    op.drop_constraint(
        op.f("fk_guard_events_message_id_messages"), "guard_events", type_="foreignkey"
    )
    op.drop_column("guard_events", "message_id")
    op.drop_index("ix_messages_conversation_created", table_name="messages")
    op.drop_table("message_translations")
    op.drop_table("lens_annotations")
    op.drop_table("messages")
    op.drop_table("guard_events")
    op.drop_table("deposit_parties")
    op.drop_table("deposit_ledger_entries")
    op.drop_index("ix_trust_events_profile_created", table_name="trust_events")
    op.drop_table("trust_events")
    op.drop_table("reviews")
    op.drop_table("deposit_agreements")
    op.drop_table("conversations")
    op.drop_table("completion_confirmations")
    op.drop_table("collaboration_members")
    op.drop_table("collaboration_deliverables")
    op.drop_table("applications")
    op.drop_table("signal_skills")
    op.drop_table("signal_roles")
    op.drop_table("collaborations")
    op.drop_index("ix_signals_status_published_at", table_name="signals")
    op.drop_table("signals")
    op.drop_index("ix_notifications_user_created", table_name="notifications")
    op.drop_table("notifications")
    op.drop_table("kb_norms")
    op.drop_table("kb_candidates")
